# Generated by Django 5.0.2 on 2024-02-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="deal_of_the_day",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
