# Generated by Django 5.0.2 on 2024-02-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0006_alter_audio_author_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="song_style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rock", "Rock"),
                    ("pop", "Pop"),
                    ("indie", "Indie"),
                    ("funky", "Funky"),
                    ("classic", "Classic"),
                    ("reggaeton", "Reggaeton"),
                    ("funky", "Funky"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
