# Generated by Django 5.0.2 on 2024-02-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0007_alter_audio_song_style"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="type",
            field=models.CharField(
                choices=[
                    ("song", "song"),
                    ("podcast", "eodcast"),
                    ("effect", "effect"),
                ],
                max_length=10,
            ),
        ),
    ]
